# Generated by Django 3.2.5 on 2022-10-16 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0002_followerinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowerInfo',
        ),
    ]
