# Generated by Django 3.2.5 on 2022-10-16 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0004_alter_follower_subscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='subscriber',
            new_name='subscribers',
        ),
    ]
