# docker-compose.yml
version: '3.8'
services:
  web:
    build: ./ai_site
    command: sh ./prestart.sh
    container_name: web
    volumes:
      - ./ai_site:/ai_site
    env_file:
      - ai_site/.env
    expose:
      - 8000
    depends_on:
      - db

  nginx:
    build: ./nginx/iit-site-frontend
    container_name: nginx
    volumes:
      - ./ai_site:/ai_site
    ports:
      - 80:80
    depends_on:
      - web

  db:
    image: postgres:13-alpine
    container_name: database
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - ai_site/.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
volumes:
  postgres_data:
  static:
  media: