# Generated by Django 3.2.5 on 2022-05-08 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210730_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernet',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=7),
        ),
        migrations.AlterField(
            model_name='usernet',
            name='github',
            field=models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.RegexValidator(regex='^(http(s?):\\/\\/)?(www\\.)?github\\.([a-z])+\\/([A-Za-z0-9]{1,})+\\/?$')]),
        ),
        migrations.AlterField(
            model_name='usernet',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='usernet',
            name='phone',
            field=models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(regex='^\\+375(17|29|33|44)[0-9]{3}[0-9]{2}[0-9]{2}$')]),
        ),
    ]
