# Generated by Django 3.2.5 on 2022-12-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_usernet_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='technology/'),
        ),
        migrations.AlterField(
            model_name='usernet',
            name='first_login',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usernet',
            name='phone',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='usernet',
            name='technology',
            field=models.ManyToManyField(blank=True, related_name='user', to='profiles.Technology'),
        ),
    ]
